{{- if  .Values.adminAccess -}}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "tektonClean.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "tektonClean.serviceAccountName" . }} 
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "tektonClean.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end -}}
