apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: clean-pipelineruns
  labels:
    app: clean-pipelineruns
spec:
  schedule: "{{ .Values.config.schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
        {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
              {{- toYaml . | nindent 12 }}
        {{- end }}
          serviceAccountName: {{ include "tektonClean.serviceAccountName" . }}
          restartPolicy: OnFailure
          containers:
          - name: {{ .Chart.Name }}
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            securityContext:
                {{- toYaml .Values.securityContext | nindent 14 }}
            env:
              - name: API_URL
                value: "{{ .Values.config.apiUrl }}" 
              - name: MAX_DAYS
                value: "{{ .Values.config.maxDays }}"
            {{- if eq .Values.adminAccess false }}
              - name: NAMESPACE
                value: {{ .Release.Namespace }} 
            {{- end }}

