{{- if eq .Values.adminAccess false -}}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "tektonClean.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "tektonClean.serviceAccountName" . }} 
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "tektonClean.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end -}}
